#define __ICON_SIZE_INVALID          0
#define __ICON_SIZE_MENU             1
#define __ICON_SIZE_SMALL_TOOLBAR    2
#define __ICON_SIZE_LARGE_TOOLBAR    3
#define __ICON_SIZE_BUTTON           4
#define __ICON_SIZE_DND              5
#define __ICON_SIZE_DIALOG           6


#define __ABOUT                      1
#define __ADD                        2
#define __APPLY                      3
#define __BOLD                       4
#define __CANCEL                     5
#define __CDROM                      6
#define __CLEAR                      7
#define __CLOSE                      8
#define __COLOR_PICKER               9
#define __CONNECT                    10
#define __CONVERT                    11
#define __COPY                       12
#define __CUT                        13
#define __DELETE                     14
#define __DIALOG_AUTHENTICATION      15
#define __DIALOG_ERROR               16
#define __DIALOG_INFO                17
#define __DIALOG_QUESTION            18
#define __DIALOG_WARNING             19
#define __DIRECTORY                  20
#define __DISCONNECT                 21
#define __DND                        22
#define __DND_MULTIPLE               23
#define __EDIT                       24
#define __EXECUTE                    25
#define __FILE                       26
#define __FIND                       27
#define __FIND_AND_REPLACE           28
#define __FLOPPY                     29
#define __FULLSCREEN                 30
#define __GO_BACK                    31
#define __GO_DOWN                    32
#define __GO_FORWARD                 33
#define __GO_UP                      34
#define __GOTO_BOTTOM                35
#define __GOTO_FIRST                 36
#define __GOTO_LAST                  37
#define __GOTO_TOP                   38
#define __HARDDISK                   39
#define __HELP                       40
#define __HOME                       41
#define __INDENT                     42
#define __INDEX                      43
#define __INFO                       44
#define __ITALIC                     45
#define __JUMP_TO                    46
#define __JUSTIFY_CENTER             47
#define __JUSTIFY_FILL               48
#define __JUSTIFY_LEFT               49
#define __JUSTIFY_RIGHT              50
#define __LEAVE_FULLSCREEN           51
#define __MEDIA_FORWARD              52
#define __MEDIA_NEXT                 53
#define __MEDIA_PAUSE                54
#define __MEDIA_PLAY                 55
#define __MEDIA_PREVIOUS             56
#define __MEDIA_RECORD               57
#define __MEDIA_REWIND               58
#define __MEDIA_STOP                 59
#define __MISSING_IMAGE              60
#define __NETWORK                    61
#define __NEW                        62
#define __NO                         63
#define __OK                         64
#define __OPEN                       65
#define __PASTE                      66
#define __PREFERENCES                67
#define __PRINT                      68
#define __PRINT_PREVIEW              69
#define __PROPERTIES                 70
#define __QUIT                       71
#define __REDO                       72
#define __REFRESH                    73
#define __REMOVE                     74
#define __REVERT_TO_SAVED            75
#define __SAVE                       76
#define __SAVE_AS                    77
#define __SELECT_COLOR               78
#define __SELECT_FONT                79
#define __SORT_ASCENDING             80
#define __SORT_DESCENDING            81
#define __SPELL_CHECK                82
#define __STOP                       83
#define __STRIKETHROUGH              84
#define __UNDELETE                   85
#define __UNDERLINE                  86
#define __UNDO                       87
#define __UNINDENT                   88
#define __YES                        89
#define __ZOOM_100                   90
#define __ZOOM_FIT                   91
#define __ZOOM_IN                    92
#define __ZOOM_OUT                   93
